# Generated by Django 4.2 on 2023-10-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_song',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
