# Generated by Django 4.2 on 2023-10-17 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_playback'),
        ('users', '0003_user_current_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_song',
        ),
        migrations.AddField(
            model_name='user',
            name='playback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify.playback'),
        ),
    ]
