# Generated by Django 4.2 on 2023-10-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_current_song_user_playback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playback',
        ),
    ]
