# Generated by Django 4.2 on 2023-07-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='user',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
