# Generated by Django 4.2 on 2023-10-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
            ],
        ),
    ]
