# Generated by Django 4.2 on 2023-10-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_current_song_user_playback'),
        ('spotify', '0010_playback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playback',
            new_name='CurrentPlayback',
        ),
    ]
