# Generated by Django 4.2 on 2023-10-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0012_rename_currentplayback_playback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playback',
            old_name='artist',
            new_name='artists',
        ),
    ]
