# Generated by Django 4.2 on 2023-11-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0015_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playback',
            name='cover',
            field=models.URLField(default='https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228'),
            preserve_default=False,
        ),
    ]
